rules = [
  OrganizeImports
  RemoveUnused
  DisableSyntax
]

OrganizeImports {
  groupedImports = Merge
  removeUnused = true
  targetDialect = Scala3
}

DisableSyntax {
  noVars = true
  noNulls = true
  noThrows = true
  noAwait = true
  noXml = true
  noFinalize = true
}
